#!/usr/bin/env php
<?php

require __DIR__ . '/../vendor/autoload.php';
require __DIR__ . '/vendor/autoload.php';

$app = new \Foris\Demo\Sdk\Application();
$artisan = new \Foris\Demo\Sdk\Console\Application($app);

$artisan->run();
